### ISSUE TITLE
Package name changed?

### ISSUE THREAD

**Issue by IzzySoft** [xRahul/GroupingMessages#14]
Did you change the package name on purpose? Until v1.3 it was `in.rahulja.groupingmessages` – but the APK attached to v1.4 identifies as `in.rahulja.ficsavemiddleware` (and thus is not considered an update to the former).

**Comment by xRahul** [comment]
my bad, seems like a typo in copy pasting. I'll fix it right now

**Comment by xRahul** [comment]
Added the new release

**Comment by IzzySoft** [comment]
Thanks! Good that I asked (and not just assumed a new package id) :rofl: New package looks good (see [here](https://apt.izzysoft.de/fdroid/index/apk/in.rahulja.groupingmessages) – apart from the fact that it's tagged 1.5 but identifies as 1.4 :open_mouth:

**Comment by xRahul** [comment]
Hmm.. Let me see what is left. I did check to change it from 1.4 to 1.5. Do you get the version from latest version link?

**Comment by IzzySoft** [comment]
From the tag, yes. And as the only other v1.4 was that with the "changed package id", I couldn't actually have taken the older version by accident :wink:

    $ wget -q https://github.com/xRahul/GroupingMessages/releases/download/1.5/GroupingMessages.1.5.apk
    $ pinfo GroupingMessages.1.5.apk
    package: name='in.rahulja.groupingmessages' versionCode='14' versionName='1.4' platformBuildVersionName=''

`pinfo` is an alias on `aapt` which extracts package details.

**Comment by IzzySoft** [comment]
One last question, @xRahul: if the app does all work on-device (as the description says), what for is the Internet permission needed?
