### ISSUE TITLE
v1.4 coming in the APK of v1.5

### ISSUE THREAD

**Issue by xRahul** [xRahul/GroupingMessages#16]
From the tag, yes. And as the only other v1.4 was that with the "changed package id", I couldn't actually have taken the older version by accident :wink:

    $ wget -q https://github.com/xRahul/GroupingMessages/releases/download/1.5/GroupingMessages.1.5.apk
    $ pinfo GroupingMessages.1.5.apk
    package: name='in.rahulja.groupingmessages' versionCode='14' versionName='1.4' platformBuildVersionName=''

`pinfo` is an alias on `aapt` which extracts package details.

_Originally posted by @IzzySoft in https://github.com/xRahul/GroupingMessages/issues/14#issuecomment-451838912_

**Comment by xRahul** [comment]
@IzzySoft Everytime I'm building it after cleaning, output APK shows v1.4. Do you know anything I can try here?

**Comment by xRahul** [comment]
I tried a few things, seems like using single quotes fixed it somehow. I've replaced the apk witht he correct one. Can you check now?

**Comment by IzzySoft** [comment]
At the moment I'm not on the right machine. Will test this evening (hopefully). But if the APK attached to the v1.5 tag now shows the corresponding versionCode (15) and versionName (1.5), it should auto-update (which then should be visible after the sync, at about 8pm CET (7pm UTC), which you can verify [here](https://apt.izzysoft.de/fdroid/index/apk/in.rahulja.groupingmessages) if my response takes too long 😉 

Thanks again!

**Comment by xRahul** [comment]
Ah, sure. Also, I have a couple other apps too if you want to add them:
https://github.com/xRahul/FicsaveMiddleware/releases/latest
https://github.com/xRahul/NotifyAvailability/releases/latest

**Comment by IzzySoft** [comment]
Did not update automatically, as v1.4 was marked 1.5 o_O Fixed that manually now, should show up tomorrow evening (or earlier should I trigger a manual sync).

Thanks for the pointers to your other apps, will take a look and let you know!

**Comment by IzzySoft** [comment]
Ugh. Ficsave contains Firebase and Google Analytics. Is it possible to have a tracker free version?

The other one should be available in a few minuts. Thanks!

**Comment by xRahul** [comment]
Yeah, I was planning to have a version without them. fdroid doesn't accept apps witht hose which is really cool imo.

**Comment by xRahul** [comment]
Creating an issue in FicsaveMiddleware for it, and closing this one

**Comment by IzzySoft** [comment]
Ping me from there when it's ready, I gladly include it with my repo then. Thanks again!
